week_5/random_word/apps/rwg/urls.py
from django.conf.urls import url
from . import views

app_name = 'rwg'

urlpatterns = [
    url('^$', views.index, name='index'),
    url('^random_word$', views.generate, name='generate'),
    url('^reset$', views.reset, name='reset'),
]

week_5/random_word/random_word/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.rwg.urls')),
    url(r'^admin/', admin.site.urls),
]

week_5/random_word/apps/rwg/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, HttpResponse
from django.utils.crypto import get_random_string

# Create your views here.
def index(request):
    try:
        request.session['attempt']
    except:
        request.session['attempt'] = 0

    return render(request, 'index.html')

def generate(request):
    request.session['attempt'] += 1
    request.session['random_word'] = get_random_string(length=14)
    return redirect('/')

def reset(request):
    del request.session['attempt']
    del request.session['random_word']
    return redirect('/')

week_5/random_word/apps/rwg/templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Random Word</title>
    </head>
    </head>
    <body>
        <div id="wrapper">
            <p>Random Word (attempt #{{request.session.attempt}})</p>
            <h1 id="random_word">{{request.session.random_word|upper }}</h1>
            <a href="{% url 'rwg:generate' %}"><button>Generate</button></a>
            <a href="{% url 'rwg:reset' %}"><button>Reset</button></a>
        </div>
    </body>
</html>